from typing import Protocol

from rmit_society.engagement.models import Block, Follow, Vote


class EngagementRepository(Protocol):
    def get_post(self, content_id: str) -> object | None: ...
    def get_comment(self, content_id: str) -> object | None: ...
    def get_user(self, user_id: str) -> object | None: ...
    def put_vote(self, vote: Vote) -> bool: ...
    def delete_vote(self, content_id: str, user_id: str) -> bool | None: ...
    def increment_counter(self, content_id: str, field: str, delta: int) -> None: ...
    def put_follow(self, follow: Follow) -> bool: ...
    def delete_follow(self, follower_user_id: str, target_user_id: str) -> None: ...
    def put_block(self, block: Block) -> bool: ...
    def delete_block(self, blocker_user_id: str, target_user_id: str) -> None: ...
