# RMIT Society — local dev convenience targets.

# Load local .env if present; otherwise use tracked MiniStack defaults.
ifneq ($(wildcard .env),)
include .env
else
include .env.example
endif
export

# MiniStack defaults (mirror .env.example) so a bare target never hits real AWS.
AWS_ENDPOINT_URL    ?= http://localhost:4566
AWS_REGION          ?= ap-southeast-2
AWS_DEFAULT_REGION  ?= ap-southeast-2
AWS_ACCESS_KEY_ID   ?= 000000000000
AWS_SECRET_ACCESS_KEY ?= test

.PHONY: up down ps health deploy-local deploy dev-backend web build-backend lint test

## Start MiniStack (+ stackport) in Docker.
up:
	docker compose up -d

## Stop MiniStack without deleting state.
down:
	docker compose down

## Show MiniStack container status.
ps:
	docker compose ps

## Health-check MiniStack.
health:
	curl -fsS http://localhost:4566/_ministack/health && echo

## Provision local AWS infra against MiniStack (idempotent).
deploy-local: health
	cd backend && uv run python ../infra/deploy.py --stage local

## Alias for deploy-local.
deploy: deploy-local

## Run the FastAPI backend locally with auto-reload.
dev-backend:
	cd backend && set -a && source ../.cloudpulse/local.env 2>/dev/null || true && set +a && rtk uv run uvicorn rmit_society.server:app --reload --app-dir src --port 8000

## Print Cognito variables generated by deploy-local.
cognito-env:
	@rtk cat .cloudpulse/local.env

## Upload a built frontend dist/ to the local web bucket.
.PHONY: web
web:
	cd backend && uv run python ../infra/deploy.py --stage local --web-dist apps/web/dist

## Build the EC2 backend image (unsupported until worker wired).
build-backend:
	cd backend && uv run python ../infra/deploy.py --stage local --build-backend

## Backend checks (run from backend/).
lint:
	cd backend && uv run ruff check . && uv run mypy

## Backend tests.
test:
	cd backend && uv run pytest

## Frontend checks.
.PHONY: fe-check
fe-check:
	cd apps/web && pnpm lint && pnpm test && pnpm build
