from __future__ import annotations

from typing import Protocol

from rmit_society.domain.content import Comment, ContentVersion, Post
from rmit_society.domain.engagement import Block, Follow, Notification, Report, Vote
from rmit_society.domain.events import AuditEvent, Upload
from rmit_society.domain.moderation import Appeal, ModerationDecisionRecord, ModerationJob
from rmit_society.domain.societies import Society, SocietyMembership
from rmit_society.domain.users import User


class Page[T](Protocol):
    """A stable-cursor page of typed records."""

    items: list[T]
    next_cursor: str | None


class UserRepository(Protocol):
    def get_user(self, user_id: str) -> User | None: ...
    def get_user_by_cognito_sub(self, cognito_sub: str) -> User | None: ...
    def link_cognito_sub(self, cognito_sub: str, user_id: str) -> None: ...
    def get_user_by_handle(self, handle: str) -> User | None: ...
    def put_user(self, user: User) -> None: ...
    def update_user(self, user_id: str, **changes: object) -> None: ...
    def reserve_handle(self, handle: str, user_id: str) -> bool: ...


class SocietyRepository(Protocol):
    def create_society(self, society: Society) -> None: ...
    def get_society(self, society_id: str) -> Society | None: ...
    def update_society(self, society_id: str, **changes: object) -> None: ...
    def get_society_by_slug(self, slug: str) -> Society | None: ...
    def list_societies(self) -> list[Society]: ...
    def reserve_slug(self, slug: str, society_id: str) -> bool: ...
    def join(self, membership: SocietyMembership) -> bool: ...
    def leave(self, society_id: str, user_id: str) -> None: ...
    def is_member(self, society_id: str, user_id: str) -> bool: ...
    def is_moderator(self, society_id: str, user_id: str) -> bool: ...
    def list_members(self, society_id: str) -> list[SocietyMembership]: ...
    def list_joined(self, user_id: str) -> list[SocietyMembership]: ...
    def set_moderator(self, society_id: str, user_id: str, is_moderator: bool) -> bool: ...
    def increment_members(self, society_id: str, delta: int) -> None: ...


class ContentRepository(Protocol):
    def create_post(self, post: Post) -> None: ...
    def get_post(self, post_id: str) -> Post | None: ...
    def update_post(self, post_id: str, **changes: object) -> None: ...
    def get_post_by_society_pinned(self, society_id: str) -> list[Post]: ...
    def create_comment(self, comment: Comment) -> None: ...
    def get_comment(self, comment_id: str) -> Comment | None: ...
    def update_comment(self, comment_id: str, **changes: object) -> None: ...
    def list_comments(self, post_id: str) -> list[Comment]: ...
    def save_version(self, version: ContentVersion) -> None: ...
    def transition_state(
        self, content_id: str, expected: str, new_state: str, **changes: object
    ) -> bool: ...
    def increment_counter(self, content_id: str, field: str, delta: int) -> None: ...


class EngagementRepository(Protocol):
    def put_vote(self, vote: Vote) -> bool: ...
    def delete_vote(self, content_id: str, user_id: str) -> None: ...
    def put_follow(self, follow: Follow) -> bool: ...
    def delete_follow(self, follower_user_id: str, target_user_id: str) -> None: ...
    def put_block(self, block: Block) -> bool: ...
    def delete_block(self, blocker_user_id: str, target_user_id: str) -> None: ...
    def create_report(self, report: Report) -> bool: ...
    def list_open_reports(self) -> list[Report]: ...
    def resolve_report(self, report_id: str, state: str) -> None: ...
    def create_notification(self, notification: Notification) -> None: ...
    def list_notifications(self, user_id: str) -> list[Notification]: ...
    def mark_notification_read(self, notification_id: str, user_id: str) -> None: ...


class FeedRepository(Protocol):
    def add_feed_entry(
        self, feed_type: str, feed_id: str, content_id: str, published_at: str
    ) -> None: ...
    def remove_feed_entry(self, feed_type: str, feed_id: str, content_id: str) -> None: ...
    def list_feed(self, feed_type: str, feed_id: str) -> list[str]: ...
    def list_joined_societies(self, user_id: str) -> list[str]: ...
    def list_following(self, user_id: str) -> list[str]: ...


class ModerationRepository(Protocol):
    def create_job(self, job: ModerationJob) -> None: ...
    def get_job(self, content_id: str) -> ModerationJob | None: ...
    def update_job_state(
        self, content_id: str, state: str, decision: str, retries: int
    ) -> None: ...
    def record_decision(self, decision: ModerationDecisionRecord) -> None: ...
    def list_queue(self, state: str) -> list[str]: ...
    def create_appeal(self, appeal: Appeal) -> bool: ...
    def get_appeal(self, appeal_id: str) -> Appeal | None: ...
    def list_appeals(self, state: str) -> list[Appeal]: ...
    def update_appeal(self, appeal_id: str, **changes: object) -> None: ...
    def append_audit(self, event: AuditEvent) -> None: ...
    def list_audit(self, target_type: str, target_id: str) -> list[AuditEvent]: ...


class UploadRepository(Protocol):
    def create_upload(self, upload: Upload) -> None: ...
    def get_upload(self, upload_id: str) -> Upload | None: ...
    def update_upload(self, upload_id: str, **changes: object) -> None: ...


class IdempotencyRepository(Protocol):
    def claim(self, key: str, response: dict[str, object]) -> dict[str, object] | None: ...
    def get(self, key: str) -> dict[str, object] | None: ...


class Repository(
    UserRepository,
    SocietyRepository,
    ContentRepository,
    EngagementRepository,
    FeedRepository,
    ModerationRepository,
    UploadRepository,
    IdempotencyRepository,
    Protocol,
):
    """Complete persistence surface used by services, handlers, and workers.

    Both the DynamoDB and Postgres implementations satisfy this protocol, so
    switching the database driver is a configuration change.
    """
