"""baseline postgres schema

Revision ID: 8eab094ca607
Revises: 
Create Date: 2026-08-02 05:42:55.992685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eab094ca607'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('appeal_id', sa.String(length=64), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('appellant_user_id', sa.String(length=64), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('appeal_id')
    )
    op.create_index(op.f('ix_appeals_content_id'), 'appeals', ['content_id'], unique=False)
    op.create_index(op.f('ix_appeals_state'), 'appeals', ['state'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_target_id'), 'audit_events', ['target_id'], unique=False)
    op.create_table('blocks',
    sa.Column('blocker_user_id', sa.String(length=64), nullable=False),
    sa.Column('target_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('blocker_user_id', 'target_user_id')
    )
    op.create_table('cognito_links',
    sa.Column('cognito_sub', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('cognito_sub')
    )
    op.create_index(op.f('ix_cognito_links_user_id'), 'cognito_links', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.String(length=64), nullable=False),
    sa.Column('post_id', sa.String(length=64), nullable=False),
    sa.Column('author_user_id', sa.String(length=64), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('requires_warning', sa.Boolean(), nullable=False),
    sa.Column('media_id', sa.String(length=128), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('removed_by_moderator', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_author_user_id'), 'comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_state'), 'comments', ['state'], unique=False)
    op.create_table('content_versions',
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_id', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('content_id', 'version')
    )
    op.create_table('feed_entries',
    sa.Column('feed_type', sa.String(length=16), nullable=False),
    sa.Column('feed_id', sa.String(length=64), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.String(length=40), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('feed_type', 'feed_id', 'content_id')
    )
    op.create_table('follows',
    sa.Column('follower_user_id', sa.String(length=64), nullable=False),
    sa.Column('target_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('follower_user_id', 'target_user_id')
    )
    op.create_index(op.f('ix_follows_target_user_id'), 'follows', ['target_user_id'], unique=False)
    op.create_table('handle_reservations',
    sa.Column('handle_lower', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('handle_lower')
    )
    op.create_table('idempotency_records',
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('moderation_decisions',
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('content_id', 'created_at', 'version')
    )
    op.create_table('moderation_jobs',
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=True),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('posts',
    sa.Column('post_id', sa.String(length=64), nullable=False),
    sa.Column('author_user_id', sa.String(length=64), nullable=False),
    sa.Column('society_id', sa.String(length=64), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('requires_warning', sa.Boolean(), nullable=False),
    sa.Column('media_id', sa.String(length=128), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('removed_by_moderator', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_posts_author_user_id'), 'posts', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_posts_society_id'), 'posts', ['society_id'], unique=False)
    op.create_index(op.f('ix_posts_state'), 'posts', ['state'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('reporter_user_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('content_id', 'reporter_user_id', name='uq_report_guard')
    )
    op.create_index(op.f('ix_reports_content_id'), 'reports', ['content_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_reports_state'), 'reports', ['state'], unique=False)
    op.create_table('slug_reservations',
    sa.Column('slug_lower', sa.String(length=64), nullable=False),
    sa.Column('society_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('slug_lower')
    )
    op.create_table('societies',
    sa.Column('society_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('slug_lower', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('society_id')
    )
    op.create_index(op.f('ix_societies_slug_lower'), 'societies', ['slug_lower'], unique=True)
    op.create_table('society_memberships',
    sa.Column('society_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('is_moderator', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('society_id', 'user_id')
    )
    op.create_index(op.f('ix_society_memberships_user_id'), 'society_memberships', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('society_id', sa.String(length=64), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.Column('declared_content_type', sa.String(length=64), nullable=False),
    sa.Column('declared_size', sa.Integer(), nullable=False),
    sa.Column('quarantine_key', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('media_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index(op.f('ix_uploads_owner_user_id'), 'uploads', ['owner_user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('cognito_sub', sa.String(length=128), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('handle_lower', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('major', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_cognito_sub'), 'users', ['cognito_sub'], unique=True)
    op.create_index(op.f('ix_users_handle_lower'), 'users', ['handle_lower'], unique=True)
    op.create_table('votes',
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('institution_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('content_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_index(op.f('ix_users_handle_lower'), table_name='users')
    op.drop_index(op.f('ix_users_cognito_sub'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_uploads_owner_user_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_society_memberships_user_id'), table_name='society_memberships')
    op.drop_table('society_memberships')
    op.drop_index(op.f('ix_societies_slug_lower'), table_name='societies')
    op.drop_table('societies')
    op.drop_table('slug_reservations')
    op.drop_index(op.f('ix_reports_state'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_content_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_posts_state'), table_name='posts')
    op.drop_index(op.f('ix_posts_society_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_user_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('moderation_jobs')
    op.drop_table('moderation_decisions')
    op.drop_table('idempotency_records')
    op.drop_table('handle_reservations')
    op.drop_index(op.f('ix_follows_target_user_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_table('feed_entries')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_comments_state'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_user_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_cognito_links_user_id'), table_name='cognito_links')
    op.drop_table('cognito_links')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_audit_events_target_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_appeals_state'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_content_id'), table_name='appeals')
    op.drop_table('appeals')
    # ### end Alembic commands ###
