from typing import Protocol


class FeedRepository(Protocol):
    def add_feed_entry(
        self, feed_type: str, feed_id: str, content_id: str, published_at: str
    ) -> None: ...
    def remove_feed_entry(
        self, feed_type: str, feed_id: str, content_id: str
    ) -> None: ...
    def list_feed(
        self, feed_type: str, feed_id: str, *, limit: int = 50, cursor: str | None = None
    ) -> list[str]: ...
    def list_joined_societies(self, user_id: str) -> list[str]: ...
    def list_following(self, user_id: str) -> list[str]: ...
